# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-10-10T09:58:11+00:00

from __future__ import annotations

from pydantic import BaseModel


class Product(BaseModel):
    id: int
    name: str
    price: float
